version: '3'
services:
  app:
    container_name: docker-project
    restart: always
    build: .
    ports:
      - '80:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/studentDB
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:6
    ports:
      - '27017:27017'
